/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OCECore */

#ifndef _Included_OCECore
#define _Included_OCECore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OCECore
 * Method:    graphSize
 * Signature: ([LNode;[LEdge;)I
 */
JNIEXPORT jint JNICALL Java_OCECore_graphSize
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
