/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OCECore_IGraphResponse */

#ifndef _Included_OCECore_IGraphResponse
#define _Included_OCECore_IGraphResponse
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
