/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OCECore_Node */

#ifndef _Included_OCECore_Node
#define _Included_OCECore_Node
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
