/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OCECore_Edge */

#ifndef _Included_OCECore_Edge
#define _Included_OCECore_Edge
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
