/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OCECore_IGraphRequest */

#ifndef _Included_OCECore_IGraphRequest
#define _Included_OCECore_IGraphRequest
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
